robot:
  kinematics: 'acker'
  # length: 3.35
  # width: 1.48
  vertices: [
    # car
    # [[-0.5, 0.74], [2.85, 0.74], [2.85, -0.74], [-0.5, -0.74]],
    # [[-0.25, 0.37], [1.425, 0.37], [1.425, -0.37], [-0.25, -0.37]],
    [[-1, 1], [1, 1], [1, -1], [-1, -1]],
    [[-0.5, 0.5], [0.5, 0.5], [0.5, -0.5], [-0.5, -0.5]],

    # # mower
    # [[-1.84, 0.75], [-0.84, 0.75], [-0.84, -0.75], [-1.84, -0.75]]
    # # single pruner
    # [[2.69, -0.299], [3.27, -0.299], [3.27, -1.499], [2.69, -1.499]]
    # # kms sprayer
    # [[-2.1, 0.5], [-1.1, 0.5], [-1.1, -0.5], [-2.1, -0.5]],
    # [[-1.0, 2.15], [-0.5, 2.15], [-0.5, -2.15], [-1.0, -2.15]]
    # double pruner
    # [[3.259, -0.175], [3.559, -0.175], [3.559, -1.5], [3.259, -1.5]],
    # [[3.259, 0.175], [3.559, 0.175], [3.559, 1.5], [3.259, 1.5]]    
    ]
  wheelbase: 1.9
  name: 'square_scale'

train:
  direct_train: true
  data_size: 100000
  data_range: [-25, -25, 25, 25]
  batch_size: 256
  epoch: 5000
  valid_freq: 250
  save_freq: 500
  lr: 5e-5
  lr_decay: 0.5
  decay_freq: 1500
